spring:
  application:
    name: "auth service"
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: samuel
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update # or validate, create, create-drop, none depending on your needs
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace